# INFO411/911 Project Autoassociative Memory MLP Test

In [46]:
# ===== # IMPORTS # ===== #
import scipy
import numpy as np
import sklearn as sk
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [13]:
# ===== # IMPORTING DATASET # ===== #
# iris = datasets.load_iris()



In [16]:
print("Printing some sample data from the iris dataset")
for training_sample in list(zip(iris.data,iris.target))[:5]:
    print(training_sample)

Printing some sample data from the iris dataset
(array([5.1, 3.5, 1.4, 0.2]), 0)
(array([4.9, 3. , 1.4, 0.2]), 0)
(array([4.7, 3.2, 1.3, 0.2]), 0)
(array([4.6, 3.1, 1.5, 0.2]), 0)
(array([5. , 3.6, 1.4, 0.2]), 0)


In [18]:
# save the features and class
 
X = iris.data   	# split iris dataset into X input and Y class labels
Y = iris.target     # class[X] is output corresponding to features[X]

In [19]:
# Split the dataset into training (70%) and testing (30%)
# Note that the shuffle parameter has been used in splitting.
 
print("Splitting the data into testing and training samples")
ratio_train, ratio_test = 0.7 , 0.3
X_train, X_test, Y_train, Y_test = train_test_split(
  X, Y, 
  train_size=ratio_train,test_size=ratio_test, 
  shuffle=True
)

Splitting the data into testing and training samples


In [21]:
# data preprocessing: Before training the network we must scale the feature data
print("Data preprocessing")
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

Data preprocessing


In [51]:
print("X Train Shape: {}".format(X_train_scaled.shape))

unique, counts = np.unique(Y, return_counts=True)
print("Class Distribution: \n{}".format(dict(zip(unique, counts))))

X Train Shape: (105, 4)
Class Distribution: 
{0: 50, 1: 50, 2: 50}


In [105]:
# The MLPClassifier and MLPRegressor are sklearn implementations of NNs
iterations = 1000           # define the iterations for training over the dataset
hidden_layers = (5,)      # define the layers/depth of the NN
alpha = 1e-05               # define the learning rate
activation = 'relu'         # define the activation function in {‘identity’, ‘logistic’, ‘tanh’, ‘relu’}
solver = 'sgd'              # define the solver for weight optimization in {‘lbfgs’, ‘sgd’, ‘adam’}


print("Creating a neural network with {} layers and {} iterations"
      .format(len(hidden_layers), iterations))

mlp = MLPClassifier(
  alpha              = alpha,
  hidden_layer_sizes = (hidden_layers),
  max_iter           = iterations,
  activation         = activation,
  solver             = solver
)

Creating a neural network with 1 layers and 1000 iterations


In [106]:
# an object which represents the neural network
# Remember to use the pre-processed data and not original values for fit()
 
mlp.fit(X_train_scaled, Y_train)  # fit features over NN

C:\Users\andre\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(5,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='sgd', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [107]:
# Run the test data over the network to see the predicted outcomes.
predictions = mlp.predict(X_test_scaled)  # predict over test data

In [115]:
print("Evaluation: Mean Accuracy Train Set")
print("{:.5f}".format(mlp.score(X_train_scaled, Y_train)))

print("Evaluation: Mean Accuracy Test Set")
print("{:.5f}".format(mlp.score(X_test_scaled, Y_test)))

## evaluation metrics and analysing the accuracy/output.
print("Evaluation: Confusion Matrix")
print(confusion_matrix(Y_test, predictions))  
# all non-diagonal elements are 0 if you get 100% accuracy

print("Evaluation report:")
print(classification_report(Y_test, predictions)) 
#f1-score/accuracy

Evaluation: Mean Accuracy Train Set
0.96190
Evaluation: Mean Accuracy Test Set
0.95556
Evaluation: Confusion Matrix
[[16  0  0]
 [ 0 10  0]
 [ 0  2 17]]
Evaluation report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.83      1.00      0.91        10
           2       1.00      0.89      0.94        19

   micro avg       0.96      0.96      0.96        45
   macro avg       0.94      0.96      0.95        45
weighted avg       0.96      0.96      0.96        45

